from app.models.user import Department


def assign_department(tags: list[str]) -> Department:
    """
    Intelligent routing based on AI tags.
    Automatically assigns issues to the appropriate department
    based on the tags generated by Gemini.
    """
    if not tags:
        return Department.OTHER
    
    tag_set = set(tag.lower() for tag in tags)
    
    # First check for direct department tags (highest priority)
    if "municipality" in tag_set:
        return Department.MUNICIPALITY
    if "water_authority" in tag_set:
        return Department.WATER_AUTHORITY
    if "kseb" in tag_set:
        return Department.KSEB
    if "pwd" in tag_set:
        return Department.PWD
    
    # Fallback: Mapping logic based on issue tags
    
    # Municipality handles garbage, cleaning, sanitation
    if tag_set & {"garbage", "trash", "dumping", "cleaning", "waste", "litter", "rubbish", "sanitation", 
                  "illegal_dumping", "overflowing_bin", "plastic_waste", "food_waste", "street_litter"}:
        return Department.MUNICIPALITY
    
    # Water Authority handles water-related issues
    if tag_set & {"water", "leak", "pipe", "sewage", "drain", "drainage", "flooding", "waterlogging", 
                  "sewerage", "drainage_issue"}:
        return Department.WATER_AUTHORITY
    
    # KSEB handles electricity and lighting
    if tag_set & {"light", "pole", "wire", "electricity", "power", "streetlight", "transformer", 
                  "cable", "electrical", "broken_streetlight"}:
        return Department.KSEB
    
    # PWD handles roads and infrastructure
    if tag_set & {"road", "pothole", "tar", "pavement", "bridge", "highway", "footpath", "sidewalk", 
                  "asphalt", "road_damage", "broken_infrastructure"}:
        return Department.PWD

    return Department.OTHER
