from app.models.user import Department


def assign_department(tags: list[str]) -> Department:
    """
    Intelligent routing based on AI tags.
    Automatically assigns issues to the appropriate department
    based on the tags generated by Gemini.
    """
    if not tags:
        return Department.OTHER
    
    tag_set = set(tag.lower() for tag in tags)
    
    # Mapping logic: Tags -> Department
    
    # Municipality handles garbage, cleaning, sanitation
    if tag_set & {"garbage", "trash", "dumping", "cleaning", "waste", "litter", "rubbish", "sanitation"}:
        return Department.MUNICIPALITY
    
    # Water Authority handles water-related issues
    if tag_set & {"water", "leak", "pipe", "sewage", "drain", "drainage", "flooding", "waterlogging", "sewerage"}:
        return Department.WATER_AUTHORITY
    
    # KSEB handles electricity and lighting
    if tag_set & {"light", "pole", "wire", "electricity", "power", "streetlight", "transformer", "cable", "electrical"}:
        return Department.KSEB
    
    # PWD handles roads and infrastructure
    if tag_set & {"road", "pothole", "tar", "pavement", "bridge", "highway", "footpath", "sidewalk", "asphalt"}:
        return Department.PWD

    return Department.OTHER
